### ISSUE TITLE
Báo lỗi rồi bác ơi. 10-3-2022

### ISSUE THREAD

**Issue by sythuan92** [KangHidro/shopee-filter-sale-1k#1]
Em dùng mấy hôm thì vẫn ok hôm nay thì báo lỗi. 
URL: https://shopee.vn/flash_sale?categoryId=12&promotionId=2040173743
Em đã dùng đúng cate ID promo ID nhưng báo lỗi.  Cannot read properties of undefined (reading 'shopid')

VM784:31 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'shopid')
    at <anonymous>:31:84
(anonymous) @ VM784:31
Promise.then (async)
getInfo @ VM784:30
(anonymous) @ VM784:79
(anonymous) @ VM784:79
Promise.then (async)
(anonymous) @ VM784:75

**Comment by KangHidro** [comment]
Bác để em check thử, cơ mà lỗi vậy nhưng bác vẫn paste ra bước 10 được ý 😂
